### ISSUE TITLE
Stripe

### ISSUE THREAD

**Issue by mmiszy** [saleor/saleor-app-payment-stripe#19]
```[tasklist]
### Tasks
- [ ] https://github.com/saleor/saleor-app-payment-stripe/issues/28
- [ ] https://github.com/saleor/saleor-app-payment-stripe/issues/18
- [ ] https://github.com/saleor/saleor-app-payment-stripe/issues/27
- [ ] https://github.com/saleor/saleor-app-payment-stripe/issues/26
- [ ] https://github.com/saleor/saleor-app-payment-stripe/issues/25
- [ ] https://github.com/saleor/saleor-app-payment-stripe/issues/24
- [ ] https://github.com/saleor/saleor-app-payment-stripe/issues/23
- [ ] https://github.com/saleor/saleor-app-payment-stripe/issues/22
- [ ] https://github.com/saleor/saleor-app-payment-stripe/issues/21
- [ ] https://github.com/saleor/saleor-app-payment-stripe/issues/20
- [ ] https://github.com/saleor/saleor-app-payment-stripe/issues/57
```
